/** @typedef {{id:string,title:string,status?:string,category:string,filter:string,summary:string,tech:string,value:string,url:string,visual:string,image:string}} Project */
/** @type {readonly Project[]} */
const projects=Object.freeze([
  {id:"01",title:"ADP ↔ ServiceTitan Timesheet & Payroll Integration",category:"Integrations",filter:"integrations",summary:"Connects employee, payroll and technician activity data through mapping, business rules, validation, exception review and reconciliation.",tech:"Node.js · REST APIs · Data Mapping · Reconciliation",value:"Turns a multi-system timesheet and payroll workflow into a controlled, reviewable integration.",url:"projects/adp-servicetitan-integration.html",visual:"crm",image:"assets/images/work/1.png"},
  {id:"02",title:"Spotio ↔ ServiceTitan CRM Integration",category:"Integrations",filter:"integrations",summary:"Synchronizes sales and operational records through API and webhook workflows with matching, upsert logic, deduplication and custom-field mapping.",tech:"Node.js · REST APIs · Webhooks · Data Mapping",value:"Connects field-sales and operational workflows while preventing duplicate or mismatched records.",url:"projects/spotio-servicetitan-integration.html",visual:"crm",image:"assets/images/work/2.png"},
  {id:"03",title:"Job Costing & Operational Reporting System",category:"Data & Reporting",filter:"data-reporting",summary:"Combines operational and financial data, applies consistent costing rules and produces repeatable reporting for business review.",tech:"SQL · Data Workflows · KPI Reporting · Automation",value:"Transforms distributed job data into reconciled costing and operational views for decision-making.",url:"projects/reporting-dashboard.html",visual:"reporting",image:"assets/images/work/3.png"},
  {id:"04",title:"SEO AI & Analytics Platform",status:"In development",category:"AI & Internal Tools",filter:"ai-tools",summary:"A React and Node.js internal platform that combines search and analytics signals with reviewable AI-assisted research and recommendations.",tech:"React · Node.js · Supabase · OpenAI · GSC · GA4",value:"Creates a traceable workflow from scattered search data to prioritized content tasks.",url:"projects/seo-ai-platform.html",visual:"seo",image:"assets/images/work/4.png"},
  {id:"05",title:"Gutter Cleaning Cost Calculator",status:"Interactive prototype",category:"Web Applications",filter:"web-applications",summary:"A shortcode-based application that converts property inputs and configurable service rules into annual and long-term cost estimates.",tech:"WordPress · PHP · JavaScript · HTML · CSS",value:"Makes a multi-input pricing calculation transparent and usable in a customer-facing workflow.",url:"projects/interactive-pricing-calculator.html",visual:"calculator",image:"assets/images/work/5.png"},
  {id:"06",title:"HSS Website & Local SEO System",category:"Web & CMS",filter:"web-cms",summary:"A reusable WordPress and ACF content system for maintaining structured service and location pages with analytics support.",tech:"WordPress · ACF · PHP · GA4 · GTM · Google Search Console",value:"Provides a maintainable CMS structure for consistent service information across customer journeys.",url:"projects/hss-seo-system.html",visual:"hss",image:"assets/images/work/6.png"}
]);
const list=document.querySelector("#project-list"),preview=document.querySelector("#project-preview");
function previewMarkup(p){const fallback=p.visual==="calculator"?`<div class="preview-art calculator" aria-hidden="true"><span>Gutter Cleaning Cost Calculator</span><strong>${p.id}</strong><div class="preview-calculator-fields"><i>Linear Feet <b>120</b></i><i>Stories <b>1</b></i><i>Frequency <b>3</b></i><button tabindex="-1">Calculate</button></div><div class="preview-calculator-results"><i>Annual estimate <b>$540.00</b></i><i>20-year projected cost <b>$10,800.00</b></i></div></div>`:`<div class="preview-art ${p.visual}" aria-hidden="true"><span>${p.category}</span><strong>${p.id}</strong><i></i><i></i><i></i></div>`;const art=fallback.replace('aria-hidden="true">',`aria-hidden="true"><img class="work-preview-image" src="${p.image}" alt="" onerror="this.remove()">`);return `${art}<div class="preview-copy"><p>${p.summary}</p><dl><dt>Built with</dt><dd>${p.tech}</dd></dl><a href="${p.url}">View project <span>→</span></a></div>`}
function setPreview(p){preview.innerHTML=previewMarkup(p)}
function renderProjects(filter="all"){const visible=projects.filter(p=>filter==="all"||p.filter===filter);list.innerHTML=visible.map((p,i)=>`<article class="project-row ${i===0?"active":""}" data-project="${p.id}" tabindex="0"><div><span class="project-index">${p.id}</span><div>${p.status?`<small>${p.status}</small>`:""}<h3>${p.title}</h3><p>${p.value}</p><div class="mobile-detail">${previewMarkup(p)}</div></div></div><span class="category">${p.category}</span><a href="${p.url}" aria-label="View project: ${p.title}">View project <span>→</span></a></article>`).join("");if(visible[0])setPreview(visible[0]);list.querySelectorAll(".project-row").forEach(row=>{const activate=()=>{list.querySelectorAll(".project-row").forEach(r=>r.classList.remove("active"));row.classList.add("active");setPreview(projects.find(p=>p.id===row.dataset.project))};row.addEventListener("mouseenter",activate);row.addEventListener("focusin",activate)})}
renderProjects();
document.querySelectorAll(".filters button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(b=>{b.classList.remove("active");b.setAttribute("aria-pressed","false")});button.classList.add("active");button.setAttribute("aria-pressed","true");renderProjects(button.dataset.filter)}));
const navToggle=document.querySelector(".nav-toggle"),nav=document.querySelector(".nav");navToggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");navToggle.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");navToggle.setAttribute("aria-expanded","false")}));
