/** @typedef {{id:string,title:string,status?:string,category:string,filter:string,summary:string,tech:string,value:string,url:string,visual:string}} Project */
/** @type {readonly Project[]} */
const projects=Object.freeze([
  {id:"01",title:"SEO AI & Analytics Platform",status:"In development",category:"AI & Tools",filter:"ai-tools",summary:"An AI-powered platform that brings search and analytics data together to identify SEO opportunities and support content decisions.",tech:"React, Node.js, OpenAI, Google Search Console and GA4",value:"Turns scattered search data into prioritized content opportunities.",url:"projects/seo-ai-platform.html",visual:"seo"},
  {id:"02",title:"HSS Website & Local SEO System",category:"Content & SEO",filter:"content-seo",summary:"A WordPress website and scalable local SEO system designed around customer needs, service content, location content and search visibility.",tech:"WordPress, ACF, PHP, GA4, GTM and Google Search Console",value:"Creates a repeatable structure for service and location content.",url:"projects/hss-seo-system.html",visual:"hss"},
  {id:"03",title:"CRM Integration & Reporting System",category:"Systems",filter:"systems",summary:"An integration that connects CRM and operational data through APIs and automated workflows.",tech:"Node.js, APIs, SQL and automation",value:"Makes operational information more accurate and reliable.",url:"projects/crm-integration.html",visual:"crm"},
  {id:"04",title:"Automated Reporting Dashboard",category:"Reporting",filter:"reporting",summary:"An automated reporting system that centralizes operational data into clearer KPI dashboards.",tech:"SQL, dashboards, KPI reporting and automation",value:"Makes operational performance easier to understand.",url:"projects/reporting-dashboard.html",visual:"reporting"}
]);
const list=document.querySelector("#project-list"),preview=document.querySelector("#project-preview");
function previewMarkup(p){return `<div class="preview-art ${p.visual}" aria-hidden="true"><span>${p.category}</span><strong>${p.id}</strong><i></i><i></i><i></i></div><div class="preview-copy"><p>${p.summary}</p><dl><dt>Built with</dt><dd>${p.tech}</dd></dl><a href="${p.url}">View project <span>→</span></a></div>`}
function setPreview(p){preview.innerHTML=previewMarkup(p)}
function renderProjects(filter="all"){const visible=projects.filter(p=>filter==="all"||p.filter===filter);list.innerHTML=visible.map((p,i)=>`<article class="project-row ${i===0?"active":""}" data-project="${p.id}" tabindex="0"><div><span class="project-index">${p.id}</span><div>${p.status?`<small>${p.status}</small>`:""}<h3>${p.title}</h3><p>${p.value}</p><div class="mobile-detail">${previewMarkup(p)}</div></div></div><span class="category">${p.category}</span><a href="${p.url}" aria-label="View project: ${p.title}">View project <span>→</span></a></article>`).join("");if(visible[0])setPreview(visible[0]);list.querySelectorAll(".project-row").forEach(row=>{const activate=()=>{list.querySelectorAll(".project-row").forEach(r=>r.classList.remove("active"));row.classList.add("active");setPreview(projects.find(p=>p.id===row.dataset.project))};row.addEventListener("mouseenter",activate);row.addEventListener("focusin",activate)})}
renderProjects();
document.querySelectorAll(".filters button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(b=>{b.classList.remove("active");b.setAttribute("aria-pressed","false")});button.classList.add("active");button.setAttribute("aria-pressed","true");renderProjects(button.dataset.filter)}));
const navToggle=document.querySelector(".nav-toggle"),nav=document.querySelector(".nav");navToggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");navToggle.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");navToggle.setAttribute("aria-expanded","false")}));
